#!//bin/sh

# Started from https://gist.github.com/pgilad/5d7e4db725a906bd7aa7

# regex to validate in commit msg
commit_regex='([A-Z]{2,5}-[0-9]+|merge)'
error_msg="Aborting commit. Your commit message is missing either a JIRA Issue ('KV-1111') or 'Merge'"

if ! grep -iqE "$commit_regex" "$1"; then
    echo "$error_msg" >&2
    exit 1
fi


